In [27]:
import numpy as np

In [96]:
class sudoku():
    def __init__(self):
        """ Création de notre grille vide"""
        self.m_grid   = np.array([[1,0,0,0,0,0,0,0,4],
                                  [2,0,0,0,0,0,0,0,0],
                                  [3,0,0,0,0,0,0,0,0],
                                  [4,0,0,0,0,0,0,0,0],
                                  [5,0,0,0,0,0,0,0,0],
                                  [6,0,0,0,3,0,0,0,0],
                                  [7,0,0,0,0,0,0,0,0],
                                  [8,0,0,0,0,0,0,0,0],
                                  [9,0,0,0,0,0,0,0,0],],dtype=int)

    def set_value(self,value, indice_line, indice_col):
        self.m_grid[indice_line,indice_col] == value
        
    def found_in_row(self,value,indice_line):
        line = self.m_grid[indice_line]
        ct  = 0
        res = -1
        for i in line:
            if i == value:
                res = ct
                break
            ct+=1
        return res
    
    def found_in_col(self,value,indice_col):
        res = -1
        for i in range(9):
            if self.m_grid[i,indice_col] == value:
                res = i
                break
        return res
    
    def found_in_square(self,value,indice_row_square,indice_col_square):
        res_i = -1
        res_j = -1
        for i in range(9):
            if self.m_grid[i%3+3*indice_row_square,i//3+3*indice_col_square] == value:
                res_i = i%3
                res_j = i//3
                break
        return res_i,res_j
    
    def SOLVE(self):
        for n_ligne in range(9):
            for num in range(1,10):
                if self.found_in_row(num,n_ligne) == -1:
                    for n_col in range(9):
                        if self.found_in_col(num,n_col) == -1:
                            if self.found_in_square(num,n_ligne//3,n_col//3) == -1:
                                self.set_value(num, n_ligne, n_col)
    def print_grid(self):
        print(self.m_grid)
                    
                    
        


In [97]:
a = sudoku()

In [98]:
a.SOLVE()

In [99]:
a.print_grid()

[[1 0 0 0 0 0 0 0 4]
 [2 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0]
 [6 0 0 0 3 0 0 0 0]
 [7 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0]]


In [77]:
a.found_in_row(6,0)

0